### ISSUE TITLE
Add presentation notebook

### ISSUE THREAD

**Issue by jtpio** [jtpio/euroscipy-2022-jupyterlite-emscripten-forge#1]
We can start from this one: https://github.com/jtpio/pydata-prague-meetup-2022/blob/main/content/presentation.ipynb

And make some edits and updates.

**Comment by jtpio** [comment]
cc @martinRenou @DerThorsten for awareness I added a base notebook in https://github.com/jtpio/euroscipy-2022-jupyterlite-emscripten-forge/pull/2 that we can iterate on

**Comment by DerThorsten** [comment]
I added my first pass to the presentation in https://github.com/jtpio/euroscipy-2022-jupyterlite-emscripten-forge/pull/3

**Comment by jtpio** [comment]
Closing as completed, thanks!
